# Generated by Django 4.2.6 on 2023-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=107, verbose_name='Name')),
                ('gender', models.CharField(max_length=31, verbose_name='Gender')),
                ('address', models.CharField(max_length=1023, verbose_name='Address')),
                ('mobile_num', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
        ),
    ]
