# Generated by Django 4.2.6 on 2023-10-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_mobile_num_student_mobileno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
    ]
