GET http://localhost:8000/student

###
POST http://localhost:8000/student HTTP/1.1
content-type: application/json

{
    "name": "Shane",
    "gender": "Male",
    "address": "Matara",
    "mobileNo": "412456789",
    "dob": 10-10-2022
}