export const sampleData = [
    {
        id: 3,
        name: 'Chai',
        gender: 'Male',
        address: 'Galle',
        mobileNo: '0771234567',
        dateOfBirth: new Date('Monday, November 6, 2000'),
        age: 22,
        inEdit: false,
    },
    {
        id: 2,
        name: 'Chai',
        gender: 'Male',
        address: 'Galle',
        mobileNo: '0771234567',
        dateOfBirth: new Date('Monday, November 6, 2000'),
        age: 22,
        inEdit: false,
    },
    {
        id: 1,
        name: 'Chai',
        gender: 'Male',
        address: 'Galle',
        mobileNo: '0771234567',
        dateOfBirth: new Date('Monday, November 6, 2000'),
        age: 22,
        inEdit: false,
    },
]
